name: Building Docker images

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check Dockerfile
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    if: ${{ !contains(github.event.head_commit.message, '[skip build]') && !contains(github.event.head_commit.message, '[force build]')}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check if Dockerfile is modified
        id: check_files
        run: |
          if (git diff -s --exit-code HEAD~1 HEAD -- Dockerfile);then
            echo "::set-output name=run_job::false"
          else
            echo "::set-output name=run_job::true"
          fi

  main:
    runs-on: ubuntu-latest
    name: Build Docker Image
    needs: check
    if: ${{ (!contains(github.event.head_commit.message, '[skip build]') && needs.check.outputs.run_job == 'true') || contains(github.event.head_commit.message, '[force build]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/asciinema_playground:latest
          cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/asciinema_playground:latest
          build-args: BUILDKIT_INLINE_CACHE=1
