name: Updating Docker images

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    name: Update Docker Image
    if: "!contains(github.event.head_commit.message, '[main skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          no-cache-filters: asciinema_playground
          push: true
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/asciinema_playground:latest
          cache-from: ${{ secrets.DOCKERHUB_USERNAME }}/asciinema_playground:latest
          build-args: BUILDKIT_INLINE_CACHE=1
